#!/bin/sh

#RPM=sbcl-1.0.38-3.el6.x86_64.rpm
RPM=sbcl-1.2.11-1.fc22.x86_64.rpm

# Make sure we have our lisp environment installed.
cd $OPENSHIFT_DATA_DIR
if ! test -f usr/bin/sbcl; then
    # It's not here.  Let's download and unpack it.
    curl -0 http://rpmfind.net/linux/fedora/linux/releases/22/Everything/x86_64/os/Packages/s/$RPM > $RPM
    rpm2cpio $RPM | cpio -idmv
fi
